Update debug.yml

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -97,3 +97,19 @@ jobs:
         kubectl describe pod prometheus-kube-prometheus-stack-prometheus-0 -n monitoring
         kubectl describe pod alertmanager-kube-prometheus-stack-alertmanager-0 -n monitoring
 
+    #========================Delete applications============================
+    - name: Perform Action
+        run: |
+            if [ "$ACTION" == "destroy" ]; then
+              kubectl delete ns monitoring
+              kubectl delete ns frontend
+              kubectl delete ns backend
+              kubectl delete ns ingress-nginx
+            else
+              echo "Invalid action specified: $ACTION"
+              exit 1
+            fi
+
+    - name: Recheck the resources
+      run: |  
+        kubectl get all --all-namespaces
